### ISSUE TITLE
mesh_navigation repository ROS2 port meta issue

### ISSUE THREAD

**Issue by Cakem1x** [naturerobots/mesh_navigation#33]
Central issue for porting mesh_navigation to ROS2 humble.

Work will be done on different branches (`humble`-prefixed`), which all get merged into a new `humble` branch. When migration is finished, the `humble` branch should contain a working version of `mesh_navigation` for ROS2 humble.

This issue keeps track of other issues and ToDos related to the migration effort:
- [x] Port LVR2 to ROS2
- [x] Port `mesh_client` pkg
- [x] Port `mesh_map` pkg
- [x] Port `mbf_mesh_core` pkg
- [x] #39 
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #35

**Comment by Cakem1x** [comment]
requires porting the lvr2 pkg to ROS2

**Comment by james-yoo** [comment]
Hi, @Cakem1x 
Did you complete porting 'lvr2' to ROS 2 humble? I am struggling with compile 'lvr2' on Ubuntu 22.04.

**Comment by Cakem1x** [comment]
> Hi, @Cakem1x Did you complete porting 'lvr2' to ROS 2 humble? I am struggling with compile 'lvr2' on Ubuntu 22.04.

I did some work on it on our fork. It is not yet 100% clean I think, I still have some issues with exporting the dependencies correctly I think. That's why there is no PR on the main repository yet. But maybe the WIP state already helps you, check out the [branch](https://github.com/naturerobots/lvr2/tree/humble). 
Note: Someone also did a bit of work in order to compile lvr2 on Ubuntu 23, see this PR [branch](https://github.com/uos/lvr2/pull/15). But I think it is stale now.
